# Generated by Django 3.1.6 on 2021-09-03 18:38

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_user_id', models.CharField(blank=True, max_length=255)),
                ('stripe_access_token', models.CharField(
                    blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                 related_name='uuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
