# Generated by Django 3.1.6 on 2021-09-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210904_0341'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
