# Generated by Django 3.1.6 on 2021-10-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_campaign_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.BigIntegerField(blank=True),
        ),
    ]
