# Generated by Django 3.1.6 on 2021-10-21 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seller_email'),
        ('dashboard', '0003_auto_20211021_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.seller'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_amount',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
