# Generated by Django 3.1.6 on 2021-10-23 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20211023_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='contributors', through='dashboard.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
