# Generated by Django 3.1.6 on 2021-11-09 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211029_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
