# Generated by Django 3.1.6 on 2021-10-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfirmation',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
